/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author alema
 */
public class Formularito extends javax.swing.JFrame {

    /**
     * Creates new form Formularito
     */
    public Formularito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloPrueba = new javax.swing.JLabel();
        BotonLectorXML = new javax.swing.JButton();
        BotonEntradaManual = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVerdad = new javax.swing.JTextArea();
        BotonMostrarMapa = new javax.swing.JButton();
        BotonSimplificar = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloPrueba.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TituloPrueba.setText("CALCULADORA BOOREAL XD");
        getContentPane().add(TituloPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 47));

        BotonLectorXML.setText("xml");
        BotonLectorXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLectorXMLActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLectorXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        BotonEntradaManual.setText("entrada");
        BotonEntradaManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntradaManualActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEntradaManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        TablaVerdad.setColumns(20);
        TablaVerdad.setRows(5);
        jScrollPane1.setViewportView(TablaVerdad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        BotonMostrarMapa.setText("mostrar");
        BotonMostrarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarMapaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMostrarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        BotonSimplificar.setText("jButton4");
        getContentPane().add(BotonSimplificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        txtRutaArchivo.setText("jTextField2");
        getContentPane().add(txtRutaArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLectorXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLectorXMLActionPerformed
        Tabla_De_Verdad tabla = new Tabla_De_Verdad();
String ruta = txtRutaArchivo.getText().trim();

if (ruta.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor ingresa una ruta de archivo.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (LectorXML.cargarDesdeXML(ruta, tabla)) {
    areaTablaVerdad.setText(tabla.generarTexto());  // Mostramos tabla en área de texto
    JOptionPane.showMessageDialog(this, "XML cargado correctamente.");
} else {
    JOptionPane.showMessageDialog(this, "No se pudo cargar el XML. Verifica la ruta o el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_BotonLectorXMLActionPerformed

    private void BotonMostrarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarMapaActionPerformed
        private void BotonMostrarMapaActionPerformed(java.awt.event.ActionEvent evt) {
    if (tabla == null) {
        JOptionPane.showMessageDialog(this, "Primero carga o ingresa una tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Redirige salida a consola o futuro TextArea
    Mapita.imprimirMapaKarnaugh(tabla.getMatriz(), tabla.getCantidadVars(), tabla.getNombres());
}
    }//GEN-LAST:event_BotonMostrarMapaActionPerformed

    private void BotonEntradaManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntradaManualActionPerformed
               private void BotonEntradaManualActionPerformed(java.awt.event.ActionEvent evt) {
    Tabla_De_Verdad tabla = new Tabla_De_Verdad();
    tabla.entradaManual(); // Método ya creado

    areaTablaVerdad.setText(tabla.generarTexto());
    JOptionPane.showMessageDialog(this, "Entrada manual completada.");
} 
    }//GEN-LAST:event_BotonEntradaManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formularito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formularito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formularito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formularito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formularito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton BotonEntradaManual;
    private static javax.swing.JButton BotonLectorXML;
    private static javax.swing.JButton BotonMostrarMapa;
    private static javax.swing.JButton BotonSimplificar;
    private static javax.swing.JTextArea TablaVerdad;
    private static javax.swing.JLabel TituloPrueba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField txtRutaArchivo;
    // End of variables declaration//GEN-END:variables
}
